DESIGN_NAME: tpu_top
VERILOG_FILES: dir::src/*.sv
CLOCK_PORT: clk
CLOCK_PERIOD: 21
PL_TIME_DRIVEN: false
IO_PIN_PLACEMENT_MODE: annealing
IO_PIN_ORDER_CFG: dir::pin_order.cfg
RUN_POST_GRT_DESIGN_REPAIR: true
FP_CORE_UTIL: 30
